language: node_js

node_js:
  - 10

# 使用 xvfb 来模拟显示 GUI
services:
  - docker

# 指定要使用的浏览器以及版本
addons:
  chrome: stable

before_install:
  - echo ${TRAVIS_BUILD_DIR}/test/data
  - docker pull halverneus/static-file-server
  - docker run -d -p 8080:8080 halverneus/static-file-server -v ${TRAVIS_BUILD_DIR}/test/data:/web -e CORS=false
  - docker ps -a

before_script:
  - curl http://127.0.0.1:8080/index.html

script:
  - npm run testci

after_script:
  - npm run codecov