language: node_js

node_js:
  - 10

# 使用 xvfb 来模拟显示 GUI
services:
  - xvfb

# 指定要使用的浏览器以及版本
addons:
  chrome: stable

before_script:
  - npm run server

script:
  - npm run testci

after_script:
  - npm run codecov