language: node_js

node_js:
  - 10

# 使用 xvfb 来模拟显示 GUI
services:
  - docker
  - xvfb
# 指定要使用的浏览器以及版本
addons:
  chrome: stable

before_install:
  - docker pull halverneus/static-file-server
  - docker run -d -p 127.0.0.1:8080:8080 halverneus/static-file-server -v /test/data:/ -e CORS=false -e FOLDER=/

script:
  - npm run testci

after_script:
  - npm run codecov