language: node_js

node_js:
  - 10

# 使用 xvfb 来模拟显示 GUI
services:
  - docker
  - xvfb
# 指定要使用的浏览器以及版本
addons:
  chrome: stable

before_install:
  - docker pull halverneus/static-file-server
  - docker run -d -v /test/data:/ -p 8080:8080
  - docker ps -a

script:
  - npm run testci

after_script:
  - npm run codecov